app/accounts/urls.py
# accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("top/", views.topView.as_view(), name="top"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("profile/", views.profile, name="profile"),
    path("friend/", views.friend, name="friend"),
    path("friend/<str:friend_profile>", views.friend_profile, name="friend_profile"),
    path("example/", views.exampleView.as_view(), name="example"),
]

app/app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    path('accounts/',include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/chat/urls.py
from django.urls import path
from . import views

app_name = "chat"

urlpatterns = [
    path("<str:room_name>?name=<str:name>", views.room, name="room"),
    path("talk_list/", views.talk_list, name="talk_list"),
]

app/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from django.contrib.auth import get_user, get_user_model
import uuid
# Create your models here.



class CustomUser(AbstractUser, UserManager):

    email = models.EmailField(verbose_name="メールアドレス", unique=True, blank=False, null=False)  #emailを必須＆ユニークに設定
    thumbnail = models.ImageField(verbose_name="プロフィール画像",upload_to="images/thumbnail/", blank=True, null=True)
    comment = models.CharField(verbose_name="ひとことコメント",max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user_status = models.CharField(verbose_name="ユーザステータス",choices=[("A","online"),("B","offline"),("C","busy")], max_length=50)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    USERNAME_FIELD = 'email'   #ログオンIDをユーザ名→Emailへ変更
    REQUIRED_FIELDS = ['username']       #ユーザーを作成するために必要なキーを指定

User = get_user_model()

class Friend(models.Model):
    follo_id = models.ForeignKey(User, on_delete=models.CASCADE)
    follower_id = models.UUIDField(editable=False)
    relation = models.BooleanField(verbose_name="関係",default=False)
    status = models.CharField(verbose_name="ステータス",choices=[("A","フォロー中"),("-A","フォローされている"),("C","ブロックしている"),("-C","ブロックされている"),("D","削除されたアカウント")], max_length=50)

app/chat/models.py
from django.db import models
from django.contrib.auth import get_user, get_user_model
import uuid

# Create your models here.

User = get_user_model()


class chat_roomModel(models.Model):
    room_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    room_name = models.CharField(max_length=50)
    update_at = models.DateTimeField(auto_now=True)


class room_userModel(models.Model):
    room_id = models.ForeignKey(chat_roomModel, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    read_at = models.DateTimeField(auto_now=True)


class messageModel(models.Model):
    message_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    message = models.CharField(max_length=50)
    posted_user = models.ForeignKey(room_userModel, on_delete=models.CASCADE)
    posted_at = models.DateTimeField(auto_now=True)


class message_statusModel(models.Model):
    message_id = models.ForeignKey(messageModel, on_delete=models.CASCADE)
    read_status = models.BooleanField(default=False)
    read_count = models.IntegerField(default=0)

app/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from .models import CustomUser
from django import forms


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')
    

    def clean_username(self):
        username = self.cleaned_data.get("username")
        if '@' in username:
            raise forms.ValidationError("ユーザー名にEメールアドレスは使用できません")
        return username



class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')


class LoginForm(AuthenticationForm):
    
    pass

app/accounts/views.py
from django.urls import reverse_lazy
from django.views import generic
from .forms import CustomUserCreationForm, LoginForm
from django.contrib.auth import login
from django.shortcuts import render
from django.http.response import HttpResponseRedirect
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required

# Create your views here.


class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    template_name = "registration/signup.html"
    success_url = reverse_lazy("accounts:profile")

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        self.object = user
        return HttpResponseRedirect(self.get_success_url())


class LoginView(LoginView):
    template_name = "registration/login.html"
    form_class = LoginForm
    success_url = reverse_lazy("accounts:profile")


class LogoutView(LogoutView):
    template_name = "registration/logout.html"


class topView(generic.TemplateView):
    template_name = "registration/top.html"


class exampleView(generic.TemplateView):
    template_name = "registration/example.html"


@login_required
def profile(request):
    return render(request, "registration/profile.html")


@login_required
def friend(request):
    return render(request, "registration/friend.html")


@login_required
def friend_profile(request, friend_profile):
    return render(request, "registration/friend_profile.html", {"name": friend_profile})

app/chat/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required
def room(request, room_name, name):
    return render(request, "main/room.html", {"room_name": room_name, "name": name})


@login_required
def talk_list(request):
    return render(request, "main/talk_list.html")

app/chat/templates/main/base.html
<html>
  {% load widget_tweaks %} {% load static %}
  <head>
    <meta charset="utf-8" />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />

    <style>
      body {
        padding-top: 10px;
      }
    </style>
  </head>

  <body>
    <style>
      .header-3 {
        box-sizing: border-box;
        width: 100%;
      }

      .header-inner {
        display: flex;
        align-items: center;
        justify-content: space-between;
        max-width: 1300px;
        height: 60px;

        margin: 0 auto;
        font-size: 1.2em;
      }

      .header-nav {
        display: flex;
        align-items: center;
        padding-right: 50px;
      }

      .header-nav-item {
        display: flex;
        align-items: center;
        margin-left: 30px;
      }

      .logo img {
        padding-top: 50px;
        width: 200px;
        height: 300px;
        object-fit: contain;
      }

      .header-button {
        box-sizing: border-box;
        display: inline-block;
        padding: 0.5em 1.2em;
        font-size: 15px;
        text-decoration: none;
        cursor: pointer;
        user-select: none;
      }

      .header-logout {
        color: #999;
        font-weight: bold;
        border: 1px #00b5ad solid;
        border-radius: 3px;
      }

      .header-login {
        font-weight: bold;
        color: #fff;
        background: #00b5ad;
        border: 1px #00b5ad solid;
        border-radius: 3px;
      }

      .header-button2 {
        padding: 1em 1.2em;
      }

      .box {
        box-sizing: border-box;
        padding-left: 150px;
        padding-top: 20px;
      }

      .box-nav {
        width: 100%;
        height: 100px;
      }

      .inner-nav {
        display: flex;
        justify-content: center;
        max-width: 1200px;
        padding: 0;
        margin: 0 auto;
        line-height: 40px;
        list-style: none;
      }

      .menu {
        position: relative;
        padding: 0 4em;
        cursor: pointer;
        color: #999;
        box-sizing: border-box;
        display: inline-block;
        font-size: 20px;
        text-decoration: none;
        cursor: pointer;
        user-select: none;
      }

      .menu:not(:first-of-type)::before {
        position: absolute;
        top: 25%;
        left: 0;
        width: 1px;
        height: 50%;
        content: "";
        background: #3a3a3a;
      }

      .menu:hover {
        opacity: 0.7;
      }
    </style>
    <header class="header-3">
      <div class="header-inner">
        <div class="logo">
          <a href="{% url 'accounts:top' %}"
            ><img src="{% static "image/Tidy.png" %}"></a
          >
        </div>

        <nav class="header-nav">
          <div class="header-nav-item">
            <a
              href="{% url 'accounts:login'%}"
              class="header-button header-login"
              >ログイン</a
            >
          </div>
          <div class="header-nav-item">
            <a
              href="{% url 'accounts:logout'%}"
              class="header-button header-logout"
              >ログアウト</a
            >
          </div>
        </nav>
      </div>
      <div class="box box-nav">
        <ul class="inner-nav">
          <a href="{% url 'accounts:top'%}" class="menu">ホーム</a>
          <a href="{% url 'accounts:profile'%}" class="menu">プロフィール</a>
          <a href="{% url 'accounts:friend'%}" class="menu">友達</a>
          <a href="{% url 'chat:talk_list' %}" class="menu">メッセージ</a>
          <a href="{% url 'accounts:example' %}" class="menu">使い方</a>
        </ul>
      </div>
    </header>

    <div class="container">{% block content %}{% endblock %}</div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

app/chat/templates/main/room.html
<!-- chat/templates/chat/room.html -->
{% extends 'main/base.html'%} {% block content %} {% load static %}

<style>
  .flex {
    display: flex;
  }
  .margin {
    margin-left: 80%;
    margin-right: 0;
  }

  .padding {
    padding-top: 30px;
  }

  .img {
    border-radius: 50%;
    border: 2px solid #00b5ad;
  }
  .text {
    position: relative;
    margin-bottom: 2em;
    padding: 1.5rem 2rem;
    border-radius: 10px;
    background: #eee;
  }

  .text:before,
  .text:after {
    position: absolute;
    content: "";
    border-radius: 50%;
    background: #eee;
  }

  .text_left:before {
    left: 30px;
    bottom: -15px;
    width: 30px;
    height: 30px;
  }

  .text_left:after {
    left: 10px;
    bottom: -30px;
    width: 15px;
    height: 15px;
  }
  .text_right:before {
    right: 30px;
    bottom: -15px;
    width: 30px;
    height: 30px;
  }

  .text_right:after {
    right: 10px;
    bottom: -30px;
    width: 15px;
    height: 15px;
  }
  .chat-box {
    width: 1100px;
    height: 1000px;
    border: 1px solid #000;
    overflow-y: scroll;
  }
  .section {
    max-height: 500px;
    padding: 1rem;
    overflow-y: auto;
    direction: ltr;
    scrollbar-color: #d4aa70 #e4e4e4;
    scrollbar-width: thin;
  }
  .section::-webkit-scrollbar {
    width: 20px;
  }

  .section::-webkit-scrollbar-track {
    background-color: #e4e4e4;
    border-radius: 100px;
  }

  .section::-webkit-scrollbar-thumb {
    border-radius: 100px;
    border: 6px solid rgba(0, 0, 0, 0.18);
    border-left: 0;
    border-right: 0;
    background-color: #00b5ad;
  }
  .flex .display {
    flex: 0 1 auto;
  }
  .flex .display2 {
    flex: 1 0 auto;
  }
  .div_img {
    margin-left: 100px;
  }
  .profile {
    font-size: 30px;
    font-size: 3rem;
    position: relative;
    padding: 1.5rem;
    text-align: center;
  }

  .profile:before {
    position: absolute;
    bottom: -10px;
    left: calc(50% - 30px);
    width: 60px;
    height: 5px;
    content: "";
    border-radius: 3px;
    background: #00b5ad;
  }
  .profile:first-letter {
    font-size: 150%;
    color: #00b5ad;
  }
  .button {
    box-sizing: border-box;
    display: inline-block;
    padding: 0.5em 5em;
    font-size: 15px;
    text-decoration: none;
    cursor: pointer;
    user-select: none;
  }
  .button-login {
    font-weight: bold;
    color: #fff;
    background: #00b5ad;
    border: 1px #00b5ad solid;
    border-radius: 3px;
  }
  .cp_iptxt {
    position: relative;
    width: 60%;
    margin: 40px 3%;
  }
  .cp_iptxt input[type="text"] {
    font-size: 30px;
    box-sizing: border-box;
    width: 100%;
    padding: 0.3em;
    transition: 0.3s;
    letter-spacing: 1px;
    color: #000000;
    border: none;
    border-bottom: 3px solid #ffe692;
    background: transparent;
  }
  .ef input[type="text"]:focus {
    border-bottom: 3px solid #00b5ad;
    outline: none;
  }
</style>

<h1 id="title" class="profile"></h1>
<div class="section" id="scrollbar">
  <ul id="chat-log"></ul>
</div>
<div style="display: flex; padding-left: 100px">
  <div class="cp_iptxt">
    <label class="ef">
      <input id="chat-message-input" type="text" size="100" />
    </label>
  </div>
  <div style="padding-top: 65px">
    <input
      id="chat-message-submit"
      type="button"
      value="送信"
      class="button button-login"
    />
  </div>
</div>

{{ room_name|json_script:"room-name" }} {{ name|json_script:"name" }}
<script>
  const roomName = JSON.parse(document.getElementById("room-name").textContent);
  const Name = JSON.parse(document.getElementById("name").textContent);

  const chatSocket = new WebSocket(
    "ws://" + window.location.host + "/ws/chat/" + roomName + "/"
  );
  let element_ul = document.getElementById("chat-log");
  let count = 1;
  let self_decoded;
  let friend_decoded;

  let title = roomName.replace(/-/g, "と");

  title = title + "のチャット";
  title_h1 = document.getElementById("title");
  title_h1.innerText = title;

  chatSocket.onmessage = function (e) {
    const data = JSON.parse(e.data);
    if (data["datatype"] == "load_image") {
      let self_image = data["self-image"];
      self_image = self_image.replace(/^../g, "");
      self_image = self_image.replace(/.$/g, "");
      self_decoded = atob(self_image);

      let friend_image = data["friend-image"];
      friend_image = friend_image.replace(/^../g, "");
      friend_image = friend_image.replace(/.$/g, "");
      friend_decoded = atob(friend_image);
    } else {
      let element_div = document.createElement("div");
      let element_margin_div = document.createElement("div");
      element_margin_div.classList.add("padding");

      element_div.classList.add("flex");

      let element_p = document.createElement("p");
      let element_sub = document.createElement("p");

      datatime = data.posted_at.replace(/\d{4}-/g, "");
      datatime = datatime.replace(/.{13}$/g, "");
      if (Name == data.posted_user) {
        element_div.style.textAlign = "left";
        element_p.style.paddingLeft = "5%";
        element_p.innerText = data.message;
        element_sub.innerText = data.posted_user + " " + datatime;
        element_p.style.marginLeft = "50px"; /* 左に余白を設ける */

        element_p.classList.add("text", "text_left");
      } else {
        element_div.style.textAlign = "right";
        element_p.style.paddingRight = "5%";
        element_p.innerText = data.message;
        element_sub.innerText = data.posted_user + " " + datatime;
        element_sub.style.marginLeft = "80%";

        element_p.style.marginRight = "50px"; /* 右に余白を設ける */

        element_p.classList.add("text", "text_right");
      }
      count++;

      let element_img = document.createElement("img");

      element_img.setAttribute("width", 75);
      element_img.setAttribute("height", 75);

      element_img.classList.add("img");

      element_div2 = document.createElement("div");
      if (Name == data.posted_user) {
        element_img.setAttribute("src", "/media/" + self_decoded);
        element_div.appendChild(element_img);
        element_div.appendChild(element_p);

        element_margin_div.appendChild(element_div);

        element_ul.append(element_margin_div);
        element_ul.append(element_sub);
        let scrollbar = document.getElementById("scrollbar");

        scrollbar.scrollTo(0, scrollbar.scrollHeight);
      } else {
        element_img.setAttribute("src", "/media/" + friend_decoded);
        element_div.appendChild(element_div2);
        element_div.appendChild(element_p);
        element_div.appendChild(element_img);
        element_p.classList.add("display");
        element_img.classList.add("display");
        element_div2.classList.add("display2");

        element_margin_div.appendChild(element_div);
        element_ul.append(element_margin_div);
        element_ul.append(element_sub);
        let scrollbar = document.getElementById("scrollbar");
        scrollbar.scrollTo(0, scrollbar.scrollHeight);
      }
    }
  };

  chatSocket.onclose = function (e) {
    console.error("Chat socket closed unexpectedly");
  };

  document.querySelector("#chat-message-input").focus();
  document.querySelector("#chat-message-input").onkeyup = function (e) {
    if (e.keyCode === 13) {
      // enter, return
      document.querySelector("#chat-message-submit").click();
    }
  };

  document.querySelector("#chat-message-submit").onclick = function (e) {
    const messageInputDom = document.querySelector("#chat-message-input");
    const message = messageInputDom.value;
    chatSocket.send(
      JSON.stringify({
        message: message,
      })
    );
    messageInputDom.value = "";
  };
</script>

{% endblock %}

app/chat/templates/main/talk_list.html
{% extends 'main/base.html'%} {% block content %} {% load static %}
<style>
  .design12 {
    width: 100%;
    text-align: center;
    border-collapse: collapse;
    border-spacing: 0;
  }

  .design12 th {
    padding: 10px;
    border: solid 1px #ffffff;
    background: #778ca3;
    color: #ffffff;
  }
  .design12 td {
    background: #0eb9b1;
    padding: 10px;
    border: solid 1px #ffffff;
    color: #ffffff;
  }
  .profile {
    font-size: 30px;
    font-size: 3rem;
    position: relative;
    padding: 1.5rem;
    text-align: center;
  }

  .profile:before {
    position: absolute;
    bottom: -10px;
    left: calc(50% - 30px);
    width: 60px;
    height: 5px;
    content: "";
    border-radius: 3px;
    background: #00b5ad;
  }
  .profile:first-letter {
    font-size: 150%;
    color: #00b5ad;
  }
  a {
    text-decoration: none;
    color: #ffffff;
  }
</style>

<h1 class="profile">メッセージリスト</h1>

<div style="padding-top: 50px">
  <table class="design12" id="sample" style="font-size: 20px">
    <tr>
      <th>友達</th>
      <th>チャット</th>
    </tr>
  </table>
</div>

<script>
  let ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
  const g_socket = new WebSocket(
    ws_scheme + "://" + window.location.host + "/ws/list/"
  );
  g_socket.onmessage = (event) => {
    let data = JSON.parse(event.data);

    data_num = Object.keys(data["name_list"]).length;
    let element_sample = document.getElementById("sample");
    (async () => {
      for (let i = 0; i < data_num; i++) {
        await promise(i);
      }
    }).call();

    function promise(i) {
      return new Promise((resolve) => {
        let element_td2 = document.createElement("td");
        let element_td = document.createElement("td");
        let element_tr = document.createElement("tr");
        let element_a = document.createElement("a");
        let element_talk = document.createElement("a");
        element_a.innerText = data["name_list"][i];
        element_talk.innerText = data["room_list"][i];
        element_talk.setAttribute(
          "href",
          "../" + data["room_list"][i] + "%3Fname=" + data["self_name"][0]
        );
        element_a.setAttribute("style", "margin-right:100px;");
        element_td2.appendChild(element_a);
        element_td.appendChild(element_talk);
        let element_img = document.createElement("img");
        let thumbnail = data["img_list"][i];
        thumbnail = thumbnail.replace(/^../g, "");
        thumbnail = thumbnail.replace(/.$/g, "");
        let decoded = atob(thumbnail);
        element_img.setAttribute("src", "/media/" + decoded);
        element_img.setAttribute("width", 50);
        element_img.setAttribute("height", 50);

        element_img.setAttribute("style", "border-radius:50%; margin:0 auto; ");
        element_td2.appendChild(element_img);

        element_tr.appendChild(element_td2);
        element_tr.appendChild(element_td);

        element_sample.appendChild(element_tr);
        resolve();
      });
    }
  };
</script>
{% endblock %}